### ISSUE TITLE
Translation and transcription?

### ISSUE THREAD

**Issue by ghost** [SayantanRoy95/R-et-S#2]
Have you thought about doing a Bilingual edition of ReS? With a transcription of the original and the translation. 

I mean a page in french and one in english. That would help the possible translators to see comparatively.

I would be happy to joining the transcription.

**Comment by SayantanRoy95** [comment]
That is a good idea indeed. I will talk with my co-translator as well. But the chances that it may happen in near future is pretty slim.

**Comment by ghost** [comment]
I see. I am going to be very attentive nevertheless. Many thanks.
